version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo-db
    networks:
      - web_network

  mongo-db:
    image: mongo:latest
    container_name: fastshop-mongo-db
    networks:
      - web_network
    restart: always
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/mongodb
      - ./ops/scripts/mongo:/docker-entrypoint-initdb.d

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_shop
    networks:
      - web_network

  redis:
    image: redis:latest
    platform: linux/amd64
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - web_network

volumes:
  postgres_data:
  redis_data:
  mongodb:

networks:
  web_network:
